### ISSUE TITLE
Upload files using Globbing patterns

### ISSUE THREAD

**Issue by franhoey** [cake-contrib/Cake.Ftp#20]
It would be really useful to be able to do something like this

`FtpUploadFiles("ftp://www.mysite.com/httpdocs/", "./artifacts/**");`

To compliment it perhaps also

`FtpDeleteFiles("ftp://www.mysite.com/httpdocs/");`

**Comment by franhoey** [comment]
Happy to pick this issue up as it something I could really use

**Comment by phillipsj** [comment]
Sounds good to me.

**Comment by phillipsj** [comment]
I will hold off on doing a new release until this is completed.  If you don't think you can get to it soon, just let me know and I will create a new milestone and do a release.

**Comment by franhoey** [comment]
That makes sense, it will probably be January now.

**Comment by franhoey** [comment]
Just thinking this one through, I'm not sure Globbing will work. The intent is to be able to upload multiple files in one go, for example a folder containing files required by a website. This is likely to contain nested directories the path of which need to be maintained on the server.

Using globbing, or any absolute file path means you also need to know the root directory to ensure the directory path is maintained on the server.

A simpler implementation of this is to add an UploadDirectory(string host, string targetDirectory, DirectoryPath sourceDirectory) function

`FtpDirectory("www.mysite.com", "/httpdocs/", new DirectoryPath("./artifacts/"));`
