### ISSUE TITLE
Binary files corrupted

### ISSUE THREAD

**Issue by wexman** [cake-contrib/Cake.Ftp#4]
Files to upload are loaded into memory as utf8 text before uploading to the server. This is not only ineffective, but will corrupt binary files.

**Comment by wexman** [comment]
I have just made a pull request which should fix this.

**Comment by phillipsj** [comment]
@wexman Thanks for contributing.

**Comment by wexman** [comment]
Thanks - that was quick!

**Comment by phillipsj** [comment]
Caught me at the right time.  It is up on Nuget too.
